import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai";
import Image from 'next/image';
import deved from '../public/end.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import  {useState} from 'react';



export default function Home() {
  const  [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ""}>
      <header>
        <title>Dx Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>

      <main className='bg-white px-10 md:px-20  lg:px-40 dark:bg-gray-900 dark:text-white '>
        <section className='min-h-screen'>
       <nav className='py-10 mb-12 flex  justify-between'> 
        <h1 className='text-xl font-poppins'> Developed by Dx </h1>
        <ul className='flex items-center'>
          <li>
             <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' /> 
             </li>

          <li> <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#"> Resume</a></li>
        </ul>

       </nav>
       <div className='text-center p-10  '>
        <h2 className='text-5xl py-2 text-teal-600 font-medium'> Daniel Dx</h2>
        <h3 className='text-2xl md:text3x;   py-2 '> Developer and Designer </h3>
        <p className='text-md py-5 leading-8 text-gray-700 mx-w-xl mx-auto'> Freelancer providing services for programming and designs contents needs . Join 
          me down below and lets go cracking.
        </p>
      
       </div>
       <div className='text-5xl flex  justify-center gap-16 py-3 text-gray-200'>
<a href=""> <AiFillLinkedin /> </a>
<a href=""> <AiFillTwitterCircle /> </a>
<a href=""> <AiFillYoutube /> </a>
       </div>
<div className='relative mx-auto bg-gradient-to-r from-cyan-500 to-teal-500 overflow-hidden rounded-full w-80 h-80 mt-20 '>
<Image src={deved} alt='deved' layout='fill' objectFit='cover'/>
</div>
        </section>
        {/* Another Section */}
        <section>
          <div className='text-center'>
            <h3 className='text-3xl py-5 text-center'> Services I Offer </h3>
            <p className='text-md py-5 leading-8 text-gray-700'> Since the beginning of 
            my journey i feel free in doing all sought of remote work
            <span className='text-teal-500'> web dev has been the best </span>
             </p>
            <p className='text-md  leading-8 text-gray-700'> Creating and Building Advanced 
            Web Pages For individual ofdifferent Entities
            <span className='text-teal-500'> i offer Wild Range </span>of services
             </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10  rounded-xl my-10  '>
            <Image src={design} width={100} height={100} alt=''/>
            <h3 className='text-lg font-poppins pt-8 pb-2'> Beautiful Designs</h3>
            <p> 
           <h4 className='py-4 text-teal-500'> Design tools  i use</h4>
           <p className = "text-greay-800" >Photoshop </p>
           <p className = "text-greay-800">  Illustrator</p>
           <p className = "text-greay-800" >Figma</p>
              Creating elegant designs suited for your need  followng core desigs theory.
            </p>
            </div>
            <div className='text-center shadow-lg p-10  rounded-xl my-10  '>
            <Image src={code} width={100} height={100} alt=''/>
            <h3 className='text-lg font-poppins pt-8 pb-2'> Beautiful Designs</h3>
            <p> 
           <h4 className='py-4 text-teal-500'> Design tools  i use</h4>
           <p className = "text-greay-800" >Photoshop </p>
           <p className = "text-greay-800">  Illustrator</p>
           <p className = "text-greay-800" >Figma</p>
              Creating elegant designs suited for your need  followng core desigs theory.
            </p>
            </div>
            <div className='text-center shadow-lg p-10  rounded-xl my-10  '>
            <Image src={consulting} width={100} height={100} alt=''/>
            <h3 className='text-lg font-poppins pt-8 pb-2'> Beautiful Designs</h3>
            <p> 
           <h4 className='py-4 text-teal-500'> Design tools  i use</h4>
           <p className = "text-greay-800" >Photoshop </p>
           <p className = "text-greay-800">  Illustrator</p>
           <p className = "text-greay-800" >Figma</p>
              Creating elegant designs suited for your need  followng core desigs theory.
            </p>
            </div>
          </div>

       
        </section>
        <section>
          <h3 className='text3xl py-1 '> Portfolio </h3>
          <p> Creating Freelancing experience from across the globe </p>Since the beginning of 
            my journey i feel free in doing all sought of remote work
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image className='rounded-lg  object-cover ' width={'100'} height={'100'}  layout="responsive" src={web1} alt="" />
            </div>
            <div  className='basis-1/3 flex-1'>
              <Image  className='rounded-lg  object-cover ' width={'100'} height={'100'}  layout="responsive" src={web2} alt="" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image  className='rounded-lg  object-cover ' width={'100'} height={'100'} layout="responsive" src={web3}  alt=""/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image className='rounded-lg  object-cover ' width={'100'} height={'100'} layout="responsive" src={web4}  alt=""/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image className='rounded-lg  object-cover ' width={'100'} height={'100'} layout="responsive"  src={web5}  alt=""/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image className='rounded-lg  object-cover ' width={'100'} height={'100'} layout="responsive"  src={web6}  alt=""/>
            </div>
            </div>
        </section>
       
      </main>
    
    </div>
  )
}
